defaults: &defaults

  default: &default
    site: &site
      title: Konnyaku
      description: Blogging with multi langs
      year: 2013
      dot: ·
    
    admin: &admin
      username: admin
      password: pass
      name: Admin User

    thanks: &thanks
      Konnyaku: http://tnantoka.github.com/konnyaku/
      Rails: http://rubyonrails.org/
      Bootstrap: http://twitter.github.com/bootstrap/

    view: &view
      pagination:
        recent: 5
        admin:  20
        search: 10
      truncate: 100 
      navbar_static: true

    service: &service
      analytics: false # or UA-XXX...
      ad:
        #side: false
        side: |
          <div class="well"> 
            Side ad
          </div>
        #bottom: false
        bottom: |
          <div class="well"> 
            Bottom ad
          </div>

  en: 
    <<: *default

  ja:
    <<: *default
    site:
      <<: *site
      description: 多言語ブログエンジン
      dot: "-"

development:
  <<: *defaults

  en: &en
    site:
      <<: *site
    admin:
      <<: *admin
    thanks:
      <<: *thanks
    view:
      <<: *view
      pagination:
        recent: 2 
        admin:  2
        search: 2
      truncate: 30
    service:
      <<: *service
      analytics: UA-123

  ja: 
    <<: *en

test:
  <<: *defaults

production:
  <<: *defaults
